name: habit_tracker
description: A habit tracking mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Networking
  dio: ^5.4.3
  
  # Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.3
  
  # Navigation
  go_router: ^17.1.0
  
  # Charts
  fl_chart: ^1.1.1
  
  # Utils
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  
  # UI
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
    - assets/images/
    - assets/backgrounds/
    - assets/logos/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
